CityPrice/CityPrice/urls.py
from django.contrib import admin
from django.urls import path

from web import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.map),

    path('map/', views.map),
    path('map/map-get-points', views.mapPoints),

    path('park/', views.park),
    path('park/add', views.parkAdd),
    path('park/add-from-file',views.parkAddFromFile),
    path('park/edit/<int:nid>', views.parkEdit),
    path('park/delete/<int:nid>', views.parkDelete),

    path('district/', views.district),
    path('district/add', views.districtAdd),
    path('district/add-from-file', views.districtAddFromFile),
    path('district/edit/<int:nid>', views.districtEdit),
    path('district/delete/<int:nid>', views.districtDelete),

    path('house/', views.house),
    path('house/add', views.houseAdd),
    path('house/add-from-file', views.houseAddFromFile),
    path('house/edit/<int:nid>', views.houseEdit),
    path('house/delete/<int:nid>', views.houseDelete),

    path('school/', views.school),
    path('school/add', views.schoolAdd),
    path('school/add-from-file', views.schoolAddFromFile),
    path('school/edit/<int:nid>', views.schoolEdit),
    path('school/delete/<int:nid>', views.schoolDelete),

    path('hospital/', views.hospital),
    path('hospital/add', views.hospitalAdd),
    path('hospital/add-from-file', views.hospitalAddFromFile),
    path('hospital/edit/<int:nid>', views.hospitalEdit),
    path('hospital/delete/<int:nid>', views.hospitalDelete),

    path('test/', views.pageTest),

]

CityPrice/web/models.py
# Create your models here.
from django.db import models


class District(models.Model):
    """ District model """
    no = models.CharField(max_length=10, primary_key=True)
    name = models.CharField(max_length=30)
    population = models.FloatField()
    area = models.FloatField()

    def __str__(self):
        return self.name


class Neighbourhood(models.Model):
    """ Neighbourhood model """
    ID = models.AutoField(primary_key=True)
    name = models.CharField(max_length=100)
    # location = models.CharField(max_length=100)
    district = models.ForeignKey(to=District, to_field='no', on_delete=models.CASCADE)
    longitude = models.FloatField(default=0)
    latitude = models.FloatField(default=0)

    # foreign key & delete the recode if the district is deleted
    # district = models.ForeignKey(to=District, to_field='no', on_delete=models.CASCADE)
    # set null if the district is deleted
    # district = models.ForeignKey(to=District, to_field='no', on_delete=models.SET_NULL, null=True)
    price = models.FloatField()


# class Location(models.Model):
#     """ Location model """
#     name = models.CharField(max_length=100)
#     longitude = models.FloatField()
#     latitude = models.FloatField()


class Park(models.Model):
    """ Park model """
    ID = models.AutoField(primary_key=True)
    name = models.CharField(max_length=100)
    location = models.CharField(max_length=100)
    # district = models.CharField(max_length=30)
    district = models.ForeignKey(to=District, to_field='no', on_delete=models.CASCADE)
    area = models.FloatField()


class Hospital(models.Model):
    """ Hospital model """
    ID = models.AutoField(primary_key=True)
    name = models.CharField(max_length=100)
    location = models.CharField(max_length=100)
    district = models.ForeignKey(to=District, to_field='no', on_delete=models.CASCADE)

    hospitalLevelChoices = (
        (1, '无等级'),
        (2, '一乙'),
        (3, '一甲'),
        (4, '二乙'),
        (5, '二甲'),
        (6, '三乙'),
        (7, '三甲'),
        (9,'其它')
    )
    level = models.SmallIntegerField(choices=hospitalLevelChoices)  # hospital level


class School(models.Model):
    """ School model """
    ID = models.AutoField(primary_key=True)
    name = models.CharField(max_length=100)
    location = models.CharField(max_length=100)
    district = models.ForeignKey(to=District, to_field='no', on_delete=models.CASCADE)

    schoolLevelChoices = (
        (1, '幼儿园'),
        (2, '小学'),
        (3, '初中'),
        (4, '职业高中'),
        (5, '普通高中'),
        (9,'其它')
    )
    level = models.SmallIntegerField(choices=schoolLevelChoices)  # school type

CityPrice/templates/add_from_file_error.html
{% extends 'layout.html' %}
{% block title %}Error{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h1>Oops! An Error Occurred</h1>
            <h2>{{ error }}</h2>
            <span class="text-muted">Your input: {{ input }}</span><br>
            <span class="text-muted">Error: {{ error_info }}</span>
        </div>
    </div>
{% endblock %}

CityPrice/templates/district.html
{% extends 'layout.html' %}
{% block title %}District List{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div><h1 class="mt-2">District List</h1></div>
                <div class="row">
                    <div class="col-sm">
                        <button type="button" class="btn btn-success" data-toggle="modal" data-target="#addDistrict">
                            Add District
                        </button>
                        <!--- add from file -->
                        <button type="button" class="btn btn-success" data-toggle="modal" data-target="#addDistrictFromFile">
                            Add Districts From File
                        </button>
                    </div>
                    <form method="get">
                        <div class="input-group col-sm">
                            <input type="text" name="search_name" class="form-control" placeholder="Search for..."
                                   value="{{ search_name }}">
                            <span class="input-group-btn">
                            <button class="btn btn-secondary" type="submit">Go!</button>
                        </span>
                        </div>
                    </form>
                </div>
            </div>
        </div>

        <!-- District Add Modal -->
        <div class="modal fade" id="addDistrict" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Add District</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>

                    <div class="modal-body">
                        <form id="modelForm">
                            {% csrf_token %}
                            <div class="form-row">
                                {% for field in form %}
                                    <div class="form-group col-md-6">
                                        {{ field.label }}{{ field }}
                                        <span class="text-danger">{{ field.errors.0 }}</span>
                                    </div>
                                {% endfor %}
                            </div>
                        </form>
                    </div>

                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        <button type="button" class="btn btn-primary" id="formSubmit">Submit</button>
                    </div>
                </div>
            </div>
        </div>

        <!-- District Add From File Modal -->
        <div class="modal fade" id="addDistrictFromFile" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <form id="districtsForm" method="post" action="add-from-file" enctype="multipart/form-data">
                        {% csrf_token %}

                        <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalLabel">Add Districts</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>

                        <div class="modal-body">
                            <label for="districtsFile">Choose a txt file to upload<br>Format: no | name | population (k) | area (km2)</label>
                            <input type="file" name="districtFile">
                        </div>

                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                            <button type="submit" class="btn btn-primary" id="formSubmit">Submit</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>

        <!-- District Add Success Popup -->
        {#        <div class="position-fixed top-0 left p-3" style="z-index: 5; left: 0; top: 0;">#}
        {#            <div id="liveToast" class="toast hide" role="alert" aria-live="assertive" aria-atomic="true" data-delay="2000">#}
        {#                <div class="toast-header">#}
        {#                    <img src="..." class="rounded mr-2" alt="...">#}
        {#                    <strong class="mr-auto">Bootstrap</strong>#}
        {#                    <small>11 mins ago</small>#}
        {#                    <button type="button" class="ml-2 mb-1 close" data-dismiss="toast" aria-label="Close">#}
        {#                        <span aria-hidden="true">&times;</span>#}
        {#                    </button>#}
        {#                </div>#}
        {#                <div class="toast-body">#}
        {#                    Hello, world! This is a toast message.#}
        {#                </div>#}
        {#            </div>#}
        {#        </div>#}

        <!-- table -->
        <table class="table table-bordered mt-3">
            <caption>District List</caption>
            <thead>
            <tr>
                <th scope="col">No.</th>
                <th scope="col">Name</th>
                <th scope="col">Area (km2)</th>
                <th scope="col">Population (k)</th>
                <th scope="col">Operation</th>
            </tr>
            </thead>
            <tbody>

            {% for filed in districts %}
                <tr>
                    <th scope="row">
                        {{ filed.no }}
                    </th>
                    <td>
                        {{ filed.name }}
                    </td>
                    <td>
                        {{ filed.area }}
                    </td>
                    <td>
                        {{ filed.population }}
                    </td>
                    <td>
                        <a class="btn-sm btn-primary" href="/district/edit/{{ filed.no }}" role="button">Edit</a>
                        <a class="btn-sm btn-danger" href="/district/delete/{{ filed.no }}" role="button">Delete</a>
                    </td>
                </tr>
            {% endfor %}

            </tbody>
        </table>

    </div>
{% endblock %}

{% block script %}
    <script>
        $(function () {
            bindBtnAddSubmitEvent();
        })

        function bindBtnAddSubmitEvent() {
            $('#formSubmit').click(function () {
                var data = $('#modelForm').serialize();
                $.ajax({
                    url: '/district/add',
                    type: 'POST',
                    data: data,
                    success: function (data) {
                        if (data.status == 'success') {
                            $('.toast').toast('show');
                            location.reload();
                        } else {
                            $.each(data.errors, function (key, value) {
                                $('#id_' + key).next().text(value[0]);
                            })
                        }
                    }
                })
            })
        }

    </script>

{% endblock %}

CityPrice/templates/district_edit.html
{% extends 'layout.html' %}
{% block title %}
    Edit District
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h1 class="ml-3 mt-2">Edit District</h1>
            </div>
        </div>
        <div class="container">

            <form id="park_form" method="post" novalidate>
                {% csrf_token %}
                <div class="form-row">
                    {% for field in form %}
                        <div class="form-group col-md-6">
                            {{ field.label }}{{ field }}
                            <span class="text-danger">{{ field.errors.0 }}</span>
                        </div>
                    {% endfor %}

                    <button type="submit" class="btn btn-primary">Submit</button>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

CityPrice/templates/hospital.html
{% extends 'layout.html' %}
{% block title %}Hospital List{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div><h1 class="mt-2">Hospital List</h1></div>
                <div class="row">
                    <div class="col-sm">
                        <button type="button" class="btn btn-success" data-toggle="modal" data-target="#addHospital">
                            Add Hospital
                        </button>
                        <button type="button" class="btn btn-success" data-toggle="modal" data-target="#addHospitalFromFile">
                            Add Hospitals From File
                        </button>
                    </div>
                    <form method="get">
                        <div class="input-group col-sm">
                            <input type="text" name="search_name" class="form-control" placeholder="Search for..."
                                   value="{{ search_name }}">
                            <span class="input-group-btn">
                            <button class="btn btn-secondary" type="submit">Go!</button>
                        </span>
                        </div>
                    </form>
                </div>
            </div>
        </div>

        <!-- Hospital Add Modal -->
        <div class="modal fade" id="addHospital" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Add Hospital</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>

                    <div class="modal-body">
                        <form id="modelForm">
                            {% csrf_token %}
                            <div class="form-row">
                                {% for field in form %}
                                    <div class="form-group col-md-6">
                                        {{ field.label }}{{ field }}
                                        <span class="text-danger">{{ field.errors.0 }}</span>
                                    </div>
                                {% endfor %}
                            </div>
                        </form>
                    </div>

                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        <button type="button" class="btn btn-primary" id="formSubmit">Submit</button>
                    </div>
                </div>
            </div>
        </div>

        <!-- Hospital Add From File Modal -->
        <div class="modal fade" id="addHospitalFromFile" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <form id="hospitalsForm" method="post" action="add-from-file" enctype="multipart/form-data">
                        {% csrf_token %}

                        <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalLabel">Add Hospitals</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>

                        <div class="modal-body">
                            <label for="hospitalsFile">Choose a txt file to upload<br>Format: Name | Location | District | Level<br>
                                Level: 1=无等级,
                                2=一乙,
                                3=一甲,
                                4=二乙,
                                5=二甲,
                                6=三乙,
                                7=三甲,
                                9=其它</label>
                            <input type="file" name="hospitalFile">
                        </div>

                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                            <button type="submit" class="btn btn-primary" id="formSubmit">Submit</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>

        <table class="table table-bordered mt-3">
            <caption>Hospital List</caption>
            <thead>
            <tr>
                <th scope="col">No.</th>
                <th scope="col">Name</th>
                <th scope="col">Level</th>
                <th scope="col">District</th>
                <th scope="col">Location</th>
                <th scope="col">Operation</th>
            </tr>
            </thead>
            <tbody>

            {% for filed in hospitals %}
                <tr>
                    <th scope="row">
                        {{ filed.ID }}
                    </th>
                    <td>
                        {{ filed.name }}
                    </td>
                    <td>
                        {{ filed.get_level_display }}
{#                        用 get_字段名_display 显示 choice 字段 #}
                    </td>
                    <td>
                        {{ filed.district }}
                    </td>
                    <td>
                        {{ filed.location }}
                    </td>
                    <td>
                        <a class="btn-sm btn-primary" href="/hospital/edit/{{ filed.ID }}" role="button">Edit</a>
                        <a class="btn-sm btn-danger" href="/hospital/delete/{{ filed.ID }}" role="button">Delete</a>
                    </td>
                </tr>
            {% endfor %}

            </tbody>
        </table>

    </div>
{% endblock %}

{% block script %}
    <script>
        $(function () {
            bindBtnAddSubmitEvent();
        })

        function bindBtnAddSubmitEvent() {
            $('#formSubmit').click(function () {
                var data = $('#modelForm').serialize();
                $.ajax({
                    url: '/hospital/add',
                    type: 'POST',
                    data: data,
                    success: function (data) {
                        if (data.status == 'success') {
                            $('.toast').toast('show');
                            location.reload();
                        } else {
                            $.each(data.errors, function (key, value) {
                                $('#id_' + key).next().text(value[0]);
                            })
                        }
                    }
                })
            })
        }

    </script>

{% endblock %}

CityPrice/templates/hospital_edit.html
{% extends 'layout.html' %}
{% block title %}
    Edit Hospital
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h1 class="ml-3 mt-2">Edit Hospital</h1>
            </div>
        </div>
        <div class="container">

            <form id="park_form" method="post" novalidate>
                {% csrf_token %}
                <div class="form-row">
                    {% for field in form %}
                        <div class="form-group col-md-6">
                            {{ field.label }}{{ field }}
                            <span class="text-danger">{{ field.errors.0 }}</span>
                        </div>
                    {% endfor %}

                    <button type="submit" class="btn btn-primary">Submit</button>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

CityPrice/templates/index.html
{% extends 'layout.html' %}
{% block title %}
    Welcome to City House Price Platform!
{% endblock %}

{% block content %}
    <div class="container"><h1>Welcome to City House Price Platform!</h1></div>

    {#    <iframe src="map/" style="border:0" allowfullscreen width='600px' height="600px"></iframe>#}
{% endblock %}

CityPrice/templates/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.css' %}">
    <script src="{% static 'jquery/jquery-3.6.3.js' %}"></script>
    <script src="{% static 'bootstrap/js/bootstrap.js' %}"></script>

    {% block script %}
    {% endblock %}

</head>

<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="/">HousePricePlatform</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item active">
                <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/house">House</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/park">Park</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/hospital">Hospital</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/school">School</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/district">District</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/map">Map</a>
        </ul>
    </div>
</nav>
{% block content %}

{% endblock %}
</body>
</html>

CityPrice/templates/park_add.html
{% extends 'layout.html' %}
{% block title %}
    Add a Park
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h1 class="ml-3 mt-2">Add a park</h1>
            </div>
        </div>
        <div class="container">

            <form id="park_form" method="post" novalidate>
                {% csrf_token %}
                <div class="form-row">
                    {% for field in form %}
                        <div class="form-group col-md-6">
                            {{ field.label }}{{ field }}
                            <span class="text-danger">{{ field.errors.0 }}</span>
                        </div>
                    {% endfor %}

                    <button type="submit" class="btn btn-primary">Submit</button>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

CityPrice/templates/school.html
{% extends 'layout.html' %}
{% block title %}School List{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div><h1 class="mt-2">School List</h1></div>
                <div class="row">
                    <div class="col-sm">
                        <button type="button" class="btn btn-success" data-toggle="modal" data-target="#addSchool">
                            Add School
                        </button>
                        <button type="button" class="btn btn-success" data-toggle="modal" data-target="#addSchoolFromFile">
                            Add Schools From File
                        </button>
                    </div>
                    <form method="get">
                        <div class="input-group col-sm">
                            <input type="text" name="search_name" class="form-control" placeholder="Search for..."
                                   value="{{ search_name }}">
                            <span class="input-group-btn">
                            <button class="btn btn-secondary" type="submit">Go!</button>
                        </span>
                        </div>
                    </form>
                </div>
            </div>
        </div>

        <!-- School Add Modal -->
        <div class="modal fade" id="addSchool" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Add School</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>

                    <div class="modal-body">
                        <form id="modelForm">
                            {% csrf_token %}
                            <div class="form-row">
                                {% for field in form %}
                                    <div class="form-group col-md-6">
                                        {{ field.label }}{{ field }}
                                        <span class="text-danger">{{ field.errors.0 }}</span>
                                    </div>
                                {% endfor %}
                            </div>
                        </form>
                    </div>

                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        <button type="button" class="btn btn-primary" id="formSubmit">Submit</button>
                    </div>
                </div>
            </div>
        </div>
    
        <!-- School Add From File Modal -->
        <div class="modal fade" id="addSchoolFromFile" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <form id="schoolsForm" method="post" action="add-from-file" enctype="multipart/form-data">
                        {% csrf_token %}

                        <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalLabel">Add Schools</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>

                        <div class="modal-body">
                            <label for="schoolsFile">Choose a txt file to upload<br>Format: Name | Location | District | Level<br>Level: 1=幼儿园,
                                2=小学,
                                3=初中,
                                4=职业高中,
                                5=普通高中,
                                9=其它</label>
                            <input type="file" name="schoolFile">
                        </div>

                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                            <button type="submit" class="btn btn-primary" id="formSubmit">Submit</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>


        <table class="table table-bordered mt-3">
            <caption>School List</caption>
            <thead>
            <tr>
                <th scope="col">No.</th>
                <th scope="col">Name</th>
                <th scope="col">Level</th>
                <th scope="col">District</th>
                <th scope="col">Location</th>
                <th scope="col">Operation</th>
            </tr>
            </thead>
            <tbody>

            {% for filed in schools %}
                <tr>
                    <th scope="row">
                        {{ filed.ID }}
                    </th>
                    <td>
                        {{ filed.name }}
                    </td>
                    <td>
                        {{ filed.get_level_display }}
{#                        用 get_字段名_display 显示 choice 字段 #}
                    </td>
                    <td>
                        {{ filed.district }}
                    </td>
                    <td>
                        {{ filed.location }}
                    </td>
                    <td>
                        <a class="btn-sm btn-primary" href="/school/edit/{{ filed.ID }}" role="button">Edit</a>
                        <a class="btn-sm btn-danger" href="/school/delete/{{ filed.ID }}" role="button">Delete</a>
                    </td>
                </tr>
            {% endfor %}

            </tbody>
        </table>

    </div>
{% endblock %}

{% block script %}
    <script>
        $(function () {
            bindBtnAddSubmitEvent();
        })

        function bindBtnAddSubmitEvent() {
            $('#formSubmit').click(function () {
                var data = $('#modelForm').serialize();
                $.ajax({
                    url: '/school/add',
                    type: 'POST',
                    data: data,
                    success: function (data) {
                        if (data.status == 'success') {
                            $('.toast').toast('show');
                            location.reload();
                        } else {
                            $.each(data.errors, function (key, value) {
                                $('#id_' + key).next().text(value[0]);
                            })
                        }
                    }
                })
            })
        }

    </script>

{% endblock %}